
##### Authentication and Authorization #####

### Gets a jwt token
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "login": "administrator",
  "roles": ["ADMIN"]
}

> {%
    client.global.set("jwtToken", response.body);
%}


##### Products Endpoints #####

### Gets a products
GET http://localhost:8080/api/v1/products
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

### Gets a product by id
GET http://localhost:8080/api/v1/products/1
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

### Creates a product
POST http://localhost:8080/api/v1/products
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "name": "Ford",
  "price": 50000
}

### Updates a product by id
PUT http://localhost:8080/api/v1/products/1
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "name": "Skoda",
  "price": 30000
}

### Removes a product by id
DELETE http://localhost:8080/api/v1/products/1
Authorization: Bearer {{jwtToken}}

######## Endpooints for testing and monitoring #####

### Gets actuator endpoints (use browser to access UI)
GET http://localhost:8080/actuator/health
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

### Gets actuator/prometheus (use browser to access UI)
GET http://localhost:8080/actuator/prometheus
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

### Gets h2 console (use browser to access UI)
GET http://localhost:8080/h2-console
Content-Type: application/json
Authorization: Bearer {{jwtToken}}