spring:
  datasource:
    url: jdbc:h2:mem:prod
    username: prod_user
    password: prod_pass
  jpa:
    show-sql: false
    properties:
      format_sql: true
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: false
  liquibase:
    change-log: classpath:liquibase/db/changelog/prod/db.changelog-master.xml
    enabled: true
logging:
  level:
    org.springframework.security: error